# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main


resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build Maven
    jobs:
      - job: Build
        displayName: Build
        pool: default
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.11'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'package'

  - stage: Docker
    displayName: Build image
    jobs:
    - job: Build
      displayName: Build
      pool: default
      steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          command: build
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          tags: |
            $(tag)
