version: '3.7'
services:

  pismo-test:
    image: pismo-test:3.0.0-SNAPSHOT
    ports:
      - '9090:8080'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/pismo-test-db?schema=public
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
  #      - logging.level.org.hibernate=DEBUG

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql