CREATE TABLE ACCOUNTS (
    ACCOUNT_ID serial CONSTRAINT ACCOUNT_ID_PK PRIMARY KEY,
	DOCUMENT_NUMBER VARCHAR(50) NOT NULL
);

CREATE UNIQUE INDEX ACCOUNTS_DOCUMENT_NUMBER_IDX ON ACCOUNTS (DOCUMENT_NUMBER);